### ISSUE TITLE
Load 18000*18000 image Crush

### ISSUE THREAD

**Issue by momotw** [dhoerl/PhotoScrollerNetwork#30] opened 2015-09-07 13:06 UTC
Hi, David 

Thank you for providing such a good solution.

But when I use the device (iPhone 6, iOS 8.3) to perform your demonstration,  Load full image (Space4.jpg and Space6.jpg) get crush. 

If use simulators is no crush.

This is where the problem?

Thank U   : )

**Comment by dhoerl** [comment] 2015-09-10 15:02
Two issues come to mind. First, its possible that the 64bit version of the libjpeg-turbo is missing or corrupt. The second is that the "scale" value provided to keep memory usage down is set too high, but that's unlikely. I can only test on a iPhone 5s (won't have a 6S until October) - will try to do shortly.

Note that this library writes to the file system, and the backing store for the image will be 4 bytes per pixel (most likely more due to rounding) plus additional smaller files for each of the scaled down versions.

**Comment by momotw** [comment] 2015-09-11 01:03
So, You can run current last public version for load 18000*18000 image (Space6.jpg)  to your iPhone 5S, right ?

Thank your reply.

**Comment by dhoerl** [comment] 2015-09-11 02:44
Interesting - trying to load Space6 now results in this:

2015-09-10 22:41:28.563 PhotoScrollerNetworkTurbo[6752:3969974] ZLEVELS=6
2015-09-10 22:41:28.577 PhotoScrollerNetworkTurbo[6752:3969974] FAILED to allocate 1340080128 bytes - errno3=Cannot allocate memory

Now, I think that means it is looking to nail down 1.3G of file space not memory, but its been a while since I looked at this.

Will take a bit to drill down on this. I also had to turn bitcode off.

**Comment by dhoerl** [comment] 2015-09-11 14:06
So the issue is that when images are local, meaning read from the file system, the program doesn't incrementally load them. You can see this by tracking how the 'mapWholeFile' flag is set. This project was designed with one purpose in mind - to allows huge images to be efficiently handled when read in over the internet. Others have asked about having it incrementally load images on the file system, and I wrote up an article on how one might do that - if you read it you can see that is possible but not trivial.

**Comment by dhoerl** [comment] 2020-02-11 22:12
This has been fixed in the new Swift Package - files are read in small chunks and don't eat up all memory.

**Closed by dhoerl** 2020-02-11 22:12 UTC
